### ISSUE TITLE
some html in the lesson

### ISSUE THREAD

**Issue by milobravman** [learn-co-curriculum/some-useful-tools-for-writing-react#3]
Some strange text rendering going on here. At the bottom of the lesson

<p class='util--hide'>View <a href='https://learn.co/lessons/some-useful-tools-for-writing-react'&gt;Some (Links to an external site.) Useful Tools for Writing React</a> on Learn.co and start learning to code for free.</p>

**Comment by ihollander** [comment]
Fixed by https://github.com/learn-co-curriculum/some-useful-tools-for-writing-react/commit/ecc205b9f89a68bd145dbeac5b4d36d2e2805376
